### ISSUE TITLE
Panning doesn't function in iOS example app

### ISSUE THREAD

**Issue by chownation** [SmartDeviceLink-Examples/example_navigation_app_ios#11]
Touch events don't seem to register and fire SDLTouchManagerDelegate

**Comment by joeljfischer** [comment]
Hi @chownation, if you are using a Ford Sync TDK, you need special permission from Ford in order to use touch while video streaming.

**Comment by chownation** [comment]
@joeljfischer got it, saw the note "You must have a valid and approved appId from an OEM in order to receive touch events" in doc https://smartdevicelink.com/en/guides/iOS/video-streaming-for-navigation-apps/touch-input/

With approved `appId` from Ford, possible to test using touch events on SYNC3 emulator first vs. TDK?

**Comment by joeljfischer** [comment]
Yes, if you have an approved app id you can test on a TDK.
